### ISSUE TITLE
[Feature Request] Download 'Reference materials'

### ISSUE THREAD

**Issue by takuya-takeuchi** [thdaemon/pixiv-novel-saver#3]
Hi.
Thank you for your publishing great script!!

Would you add new feature to download 'Reference materials' about series?

The example url is 
````
https://www.pixiv.net/novel/series/<series_id>/glossary/<materia_id>
````

I am writing Japanese novel in pixiv.
But pixiv has no api and it means that we can not sync between published data and local data.
For now, I treat publish data as master data.
Therefore, I copy data to stroage as backup after publish novels.

If script support to download 'Reference materials', it is easy to sync all data.

Thank you for your coperations.

**Comment by thdaemon** [comment]
Sorry, I couldn't find the glossary for series which I read, can you give me a real example?

**Comment by takuya-takeuchi** [comment]
@thdaemon 

Thank you.
unfortunately, I have already implemented this function as powershell.
So I close issue.
