### ISSUE TITLE
[Feature Request] Support for muliple ids

### ISSUE THREAD

**Issue by dundundunnn** [thdaemon/pixiv-novel-saver#8]
can you implement a function where an instance you can add multiple ids in one instance. for example, 
./novel.sh -A 121331 12121313 13133122 13213441 --with-inline-images --with-cover-image

**Comment by thdaemon** [comment]
You can specify the these arguments multiple times.

For example,
```
./novel.sh -A 12345 -A 12346 -A 12347 -s 999 -s 1000 -s 1001
```
